--[[
 * Contains all Action IDS of SERVER!
]]--

	sid =
	{
	
	NOBLE_ARMOR_QUENDOR 	= 2001, --> Noble Armor Quendor CYCS
	BK_CSHIELD 				= 2002, --> BK QUEST1
	BK_CARMOR 				= 2003, --> BK QUEST2
	ORC_FSWORD				= 2004, --> ORC FORTESS FIRE SWORD
	ORC_KARMOR				= 2005, --> ORC FORTRSS K ARM
	ORC_KAXE				= 2006, --> ORC FORTRESS K AXE
	CRUSADER_HELMET			= 2007, --> CRUSADER HELMET GSCAVE DWARFS
	BRASS_ARMOR_QUENDOR		= 2008, --> BRASS SET QUEST QUENDOR
	BRASS_LEGS_QUENDOR		= 2009,	--> BRASS SET QUEST QUENDOR
	STEEL_SHIELD_QUENDOR 	= 2010,	--> CASTELO DE ORC QUENDOR
	SCALE_ARMOR_QUENDOR		= 2011,	--> CASTELO DE ORC QUENDOR
	MIGHT_RING_QUENDOR		= 2012, --> TORRE DE DRAGON MINOS QUENDOR	
	
	}