--[[
 * Contains all Action IDS of SERVER!
]]--

	sid =
	{
	
		-- QUESTS BY CHESTS
	NOBLE_ARMOR_QUENDOR 	= 2001, --> Noble Armor Quendor CYCS
	BK_CSHIELD 				= 2002, --> BK QUEST1
	BK_CARMOR 				= 2003, --> BK QUEST2
	ORC_FSWORD				= 2004, --> ORC FORTESS FIRE SWORD
	ORC_KARMOR				= 2005, --> ORC FORTRSS K ARM
	ORC_KAXE				= 2006, --> ORC FORTRESS K AXE
	CRUSADER_HELMET			= 2007, --> CRUSADER HELMET GSCAVE DWARFS
	BRASS_ARMOR_QUENDOR		= 2008, --> BRASS SET QUEST QUENDOR
	BRASS_LEGS_QUENDOR		= 2009,	--> BRASS SET QUEST QUENDOR
	STEEL_SHIELD_QUENDOR 	= 2010,	--> CASTELO DE ORC QUENDOR
	SCALE_ARMOR_QUENDOR		= 2011,	--> CASTELO DE ORC QUENDOR
	MIGHT_RING_QUENDOR		= 2012, --> TORRE DE DRAGON MINOS QUENDOR	
	BROBE_ANCIENTQUEST		= 2013, --> ANCIENT ROOM QUEST
	QROD_ANCIENTQUEST		= 2014, --> ANCIENT ROOM QUEST
	SMALL_SAPHIRE_ANCIENT	= 2015, --> ANCIENT ROOM QUEST
	DEVIL_HELMET_ANCIENT	= 2016, --> ANCIENT ROOM QUEST
	CEM_GOLDS_CYCS			= 2017, --> 100 GOLD COIN CYCS THORN
	CEM_BOLTS_QUENDOR		= 2018, --> 100 BOLTS QUEST EAST OF QUENDOR
	ROH_QUENDORCAVES		= 2019, --> QUEST DO RING OF HEALING
	GSILK_ELFCAMP			= 2020, --> QUEST 4 GSILK!
	PLEGS_ELFCAMP			= 2021, --> PLEGS QUEST ELFCAMP THORN
	BS_QUEST_MINT			= 2022, --> QUEST OF BRIGHT SWORD
	WSTAKE_VAMP				= 2023, -- QUEST WOODEN STAKE
	BHERB_GS				= 2024, -- BLOOD HERB QUEST
	BASTSKIRT_DWORCS		= 2025, -- BAST SKIRT QUEST SALAZART
	PIRATE_EXPQUEST			= 2026, -- EXP QUEST PIRATES
	HELHEIM_EXPQUEST		= 2027, -- EXP QUEST IN HELHEIM ISLAND
	MINES_EXPQUEST			= 2028, -- EXP QUEST IN MINES!
	RAT_ROOKCAVE			= 2029, -- RAPIER QUEST ROOK
	STUDDED_SHIELDROOK		= 2030, -- TROLL QUEST IN ROOKGARD
	MACHETE_ROOK			= 2031, -- QUEST DA MACHETE IN ROOK
	CHAINARMOR_ROOK			= 2032, -- QUEST CHAIN ARMOR ROOK
	FISHING_ROD_ROOK		= 2033, -- QUEST FISIHING ROD ROOK
	VIKING_HELMET_ROOK		= 2034, -- VK HELM ROOK
	STUDDED_LEGS_ROOK		= 2035, -- STUDDED LEGS IN ROOK!
	CARLIN_SWORD_ROOK		= 2036, -- CARLIN SWORD ROOK
	KATANA_ROOK				= 2037, -- KATANA QUEST IN ROOK
	PLATE_SHIELD_ROOK		= 2038, -- PSHIELD QUEST ROOK
	SPIKE_SWORD_ROOK		= 2039, -- KATANA QUEST ROOK
	HAND_AXE_ROOK			= 2040, -- HAND AXE ROOK!
	POI_AVENGUER			= 2041, -- POI QUEST
	POI_ARBALEST			= 2042, -- POI QUET
	POI_ARCANE				= 2043, -- POI QUEST
	WYRMS_LIGHTLEGS			= 2044, -- WYRMS CAVE  IN ARACURA	
	
	--[[ VALUES PARA VERIFICAÇÕES (QUESTS, ETC) ]]--
	
	BANSHEE_FIRST			= 4002,
	BANSHEE_SECOND			= 4003,
	BANSHEE_THIRD			= 4004,
	BANSHEE_FOUR			= 4005,
	BANSHEE_FIVE			= 4006,
	BANSHEE_SIX				= 4007,
	BANSHEE_QUEENDOOR		= 4009,
	ANIHI_QUEST				= 4010,
	
	
	
	
	
		-- OUTROS
		ITEM_SHOP_ID			= 8987 --> IDENTIFICADOR DE ITEMSHOP
	}